### ISSUE TITLE
tokens are automatically banned

### ISSUE THREAD

**Issue by chainsaw11** [MainSilent/DAC#1]
all the tokens are auto banned by discord and render the whole operation useless, i have tried different methods but none has worked.
is there a fix for it?
take a look at https://github.com/Lowys-bey/DiscordAccountCreator it's an interesting approach.
also your code is spot on, props to you!

**Comment by MainSilent** [comment]
That's right but they are not useless I'm using a bug in discord register request when you pass the invite code directly It will join the user to the guild (recently there are some issues).

It does't matter if the user is banned or not but you can always use the websocket(make the user online or join them to a voice channel), this is useful for raiding.

**Comment by JokersCat** [comment]
Hey does your gen still work? 😅

**Comment by MainSilent** [comment]
The last time I checked it appears the invite request bug has been fixed by discord
